# Generated by Django 6.0.7 on 2026-07-27 19:00

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='articles/', verbose_name='تصویر مقاله')),
                ('content', ckeditor.fields.RichTextField(verbose_name='متن مقاله')),
                ('author', models.CharField(default='مدیر سایت', max_length=100, verbose_name='نویسنده')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شود؟')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
    ]
