# Generated by Django 6.0.7 on 2026-07-24 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_brand_product_brand_subcategory_brand_subcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
