# Generated by Django 6.0.7 on 2026-07-30 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_brand_slug_category_slug_subcategory_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='slug',
        ),
    ]
