# Generated by Django 6.0.7 on 2026-07-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='تهران', max_length=100, verbose_name='شهر'),
            preserve_default=False,
        ),
    ]
